### ISSUE TITLE
Get order info

### ISSUE THREAD

**Issue by 0x0xyz** [rubik/lobster#3]
How can I check the status of a given order having its id ? Is there a method to say `getOrderInfo(order_id)` and get the order state and some other info ?

**Comment by rubik** [comment]
@0x0xyz There's no method for that. However, off the top of my head, you could do it by accessing the orderbook's `arena` field, and then looking up the ID in the arena's `order_map` field.

**Comment by BatiGencho** [comment]
@rubik Thanks, I can do that and there is a method that gets me the qty and the price:

```
    pub fn get_full(&self, id: u128) -> Option<(u64, u64, usize)> {
        self.order_map
            .get(&id)
            .map(|i| (self.orders[*i].price, self.orders[*i].qty, *i))
    }
```
    
    
    But that is pretty much it - there is no info about the status of the order. Do you know how I could obtain it ?
    
    Many thanks

**Comment by rubik** [comment]
@BatiGencho If you find the order in the arena, it's assumed that the order is still valid and resting in the order book. If it's fully matched by a market order or canceled, it's removed from the arena.
